@extends('layouts.errors')
@section('title', __('Unauthorized'))
@section('code', '401')
@section('message', __('Unauthorized'))
@section('details', __('Sorry, you are not authorized to access this page.'))
