@extends('layouts.errors')
@section('title', __('Payment Required'))
@section('code', '402')
@section('message', __('Payment Required'))
@section('details', __('Sorry, you need to make a payment to access this page.'))
