@extends('layouts.errors')
@section('title', __('Method Not Allowed'))
@section('code', '405')
@section('message', __('Method Not Allowed'))
@section('details', __('The request method is not supported for this resource.'))
