@extends('layouts.errors')
@section('title', __('Page Expired'))
@section('code', '419')
@section('message', __('Page Expired'))
@section('details', __('Sorry, your session has expired. Please refresh and try again.'))
