@extends('layouts.errors')
@section('title', __('Too Many Requests'))
@section('code', '429')
@section('message', __('Too Many Requests'))
@section('details', __('Sorry, you are making too many requests to our servers.'))
