@extends('layouts.errors')
@section('title', __('Server Error'))
@section('code', '500')
@section('message', __('Server Error'))
@section('details', __('Sorry, the server encountered an error processing your request.'))
