@extends('layouts.errors')
@section('title', __('Service Unavailable'))
@section('code', '503')
@section('message', __('Service Unavailable'))
@section('details', __('Sorry, we are doing some maintenance. Please check back soon.'))
